package com.github.jelatinone.model.graph;

import com.github.jelatinone.model.struct.Identity.EdgeIdentity;

import lombok.NonNull;

/**
 * 
 * <h1>GraphReviewCause</h1>
 * 
 * Cause of a {@link GraphReview review} generation
 * 
 * @author Cody Washington
 */
public sealed interface GraphReviewCause {

  /**
   * The review was manually generated as a seed target.
   * 
   * @apiNote Used to 'jumpstart' the discovery graph when the system does
   *          not yet have any known targets to expand via.
   * 
   */
  record Origin(
      @NonNull String reference) implements GraphReviewCause {
  }

  /**
   * The review was dynamically generated by a stage implementation because a
   * parent target discovered this target.
   * 
   * @apiNote Normal graph-expansion cause. For example, we 'investigate' a parent
   *          page, extract relevant links, and create an {@link GraphEdge edge}
   *          to the parent {@link GraphNode node}, and request a review for the
   *          discovered child.
   * 
   */
  record Discovery(
      @NonNull EdgeIdentity relationalEdgeId) implements GraphReviewCause {
  }
}
