package com.github.jelatinone.model.graph;

import java.util.UUID;

import lombok.NonNull;

/**
 * 
 * <h1>GraphReviewCause</h1>
 * 
 * Cause of a {@link GraphReview review} generation
 * 
 * @author Cody Washington
 */
public sealed interface GraphReviewCause {

  /**
   * The review was manually generated as a seed target.
   * 
   * @apiNote Used to 'jumpstart' the discovery graph when the system does
   *          not yet have any known targets to expand via.
   * 
   */
  record Origin(
      @NonNull String originRef) implements GraphReviewCause {
  }

  /**
   * The review was dynamically generated by a stage implementation because it
   * produced a result that justified immediately continuing work on the same
   * target.
   * 
   * @apiNote Under normal flow conditions, this should only occur under
   *          a high-confidence gate.
   * 
   */
  record Transition(
      @NonNull UUID parentReviewId) implements GraphReviewCause {
  }

  /**
   * The review was dynamically generated by a stage implementation because a
   * parent target discovered this target.
   * 
   * @apiNote Normal graph-expansion cause. For example, we 'investigate' a parent
   *          page, extract relevant links, and create an {@link GraphEdge edge}
   *          to the parent {@link GraphNode node}, and request a review for the
   *          discovered child.
   * 
   */
  record Discover(
      @NonNull UUID relationalEdgeId) implements GraphReviewCause {
  }
}
