plugins {
  id ("java")
  id ("application")
}

dependencies {
  implementation project (":common")

  compileOnly ("org.projectlombok:lombok:1.18.42")
	annotationProcessor ("org.projectlombok:lombok:1.18.42")
	
	testCompileOnly ("org.projectlombok:lombok:1.18.42")
	testAnnotationProcessor ("org.projectlombok:lombok:1.18.42")
}