plugins {
  id ('java')
}

repositories {
  mavenCentral()
}

dependencies {
  implementation ('commons-cli:commons-cli:1.11.0')
  implementation ("org.slf4j:slf4j-simple:2.0.17")

  compileOnly ("org.projectlombok:lombok:1.18.42")
  annotationProcessor ("org.projectlombok:lombok:1.18.42")

  testImplementation ("org.junit.jupiter:junit-jupiter:5.10.2")
  testCompileOnly ("org.projectlombok:lombok:1.18.42")
  testAnnotationProcessor ("org.projectlombok:lombok:1.18.42")
}

test {
  useJUnitPlatform()
}
