package com.github.jelatinone.feature;

public enum FeatureCategory {

  URL_PARTS,
  STATUS_CODE,
  CONTENT_KIND,
  MEDIA_TYPE,
  CONTENT_LENGTH,
  PREVIEW_TEXT,

  PATH_TOKENS,
  QUERY_PARAMETER_COUNT,
  TARGET_KEYWORDS,
  LOGIN_OR_FORM_HINTS,
  TEXTBOX_OR_SEARCH_HINTS,

  OUTBOUND_LINKS,
  INTERNAL_LINK_COUNT,
  EXTERNAL_LINK_COUNT,
  REPEATED_LINK_PATTERN_COUNT,
  LISTING_LANGUAGE_HINTS,
  PAGINATION_HINTS,
  INDEX_PAGE_HINTS,
  STRUCTURED_DATA
}
